name: Dockerized Smoke Tests

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache Docker layers to speed up subsequent builds or pulls
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Caching the Docker layers
    - name: Cache Docker layers
      id: cache-docker-layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Log in to Docker Hub (optional, if pulling image)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Pull or build the Docker image (faster with cached layers)
    - name: Pull or build Docker image
      run: |
        docker pull bilaldjedovic/playwrighttest:latest || \
        docker build --cache-from=type=local,src=/tmp/.buildx-cache -t bilaldjedovic/playwrighttest:latest .

    # Run Playwright tests in Docker container
    - name: Run Playwright tests
      run: |
        docker run --rm bilaldjedovic/playwrighttest:latest

    # Upload the Playwright test report as an artifact
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: /app/playwright-report/
        retention-days: 30
