name: Dockerized Playwright Tests

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull bilaldjedovic/playwrighttest:latest

    - name: Run Playwright tests in parallel using Docker Compose
      run: |
        docker-compose up --scale playwright=7  


    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: /app/playwright-report/
        retention-days: 30


        