name: Dockerized Smoke Tests

on:
  push:
    branches: master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker buildx build --cache-from=type=local,src=~/.cache/docker --cache-to=type=local,dest=~/.cache/docker --tag my-playwright-tests .

    - name: Run Playwright tests in Docker container
      run: |
        docker run --rm my-playwright-tests

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: /app/playwright-report/
        retention-days: 30
