name: Dockerized Smoke Tests

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-playwright-tests:latest

    - name: Run Playwright tests in Docker container
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/my-playwright-tests:latest

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: /app/playwright-report/
        retention-days: 30
